// AUTO-GENERATED by Supabase MCP (mcp__supabase__generate_typescript_types).
// To regenerate, ask Claude to re-run that MCP tool.
// DO NOT EDIT BY HAND.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      _migration_id_map: {
        Row: {
          airtable_id: string
          supabase_id: string
          table_name: string
        }
        Insert: {
          airtable_id: string
          supabase_id: string
          table_name: string
        }
        Update: {
          airtable_id?: string
          supabase_id?: string
          table_name?: string
        }
        Relationships: []
      }
      adjuster_reports: {
        Row: {
          acv_amount: number | null
          adjuster_name: string | null
          airtable_id: string | null
          approval_date: string | null
          claim_id: string | null
          created_at: string | null
          deductible: number | null
          depreciation: number | null
          fields_raw: Json | null
          id: string
          line_items_count: number | null
          o_and_p_amount: number | null
          o_and_p_percent: number | null
          rcv_amount: number | null
          report_date: string | null
          report_name: string | null
          report_type: string | null
          scope_changes: string | null
          status: string | null
          updated_at: string | null
          version: number | null
        }
        Insert: {
          acv_amount?: number | null
          adjuster_name?: string | null
          airtable_id?: string | null
          approval_date?: string | null
          claim_id?: string | null
          created_at?: string | null
          deductible?: number | null
          depreciation?: number | null
          fields_raw?: Json | null
          id?: string
          line_items_count?: number | null
          o_and_p_amount?: number | null
          o_and_p_percent?: number | null
          rcv_amount?: number | null
          report_date?: string | null
          report_name?: string | null
          report_type?: string | null
          scope_changes?: string | null
          status?: string | null
          updated_at?: string | null
          version?: number | null
        }
        Update: {
          acv_amount?: number | null
          adjuster_name?: string | null
          airtable_id?: string | null
          approval_date?: string | null
          claim_id?: string | null
          created_at?: string | null
          deductible?: number | null
          depreciation?: number | null
          fields_raw?: Json | null
          id?: string
          line_items_count?: number | null
          o_and_p_amount?: number | null
          o_and_p_percent?: number | null
          rcv_amount?: number | null
          report_date?: string | null
          report_name?: string | null
          report_type?: string | null
          scope_changes?: string | null
          status?: string | null
          updated_at?: string | null
          version?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "adjuster_reports_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
        ]
      }
      billing_checklist: {
        Row: {
          airtable_id: string | null
          completed_date: string | null
          created_at: string | null
          due_date: string | null
          fields_raw: Json | null
          id: string
          item_name: string | null
          notes: string | null
          project_id: string
          status: string | null
          updated_at: string | null
        }
        Insert: {
          airtable_id?: string | null
          completed_date?: string | null
          created_at?: string | null
          due_date?: string | null
          fields_raw?: Json | null
          id?: string
          item_name?: string | null
          notes?: string | null
          project_id: string
          status?: string | null
          updated_at?: string | null
        }
        Update: {
          airtable_id?: string | null
          completed_date?: string | null
          created_at?: string | null
          due_date?: string | null
          fields_raw?: Json | null
          id?: string
          item_name?: string | null
          notes?: string | null
          project_id?: string
          status?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "billing_checklist_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      claims: {
        Row: {
          action_items: Json | null
          acv: number | null
          address: string
          adjuster_contact_info: Json | null
          adjuster_email: string | null
          adjuster_name: string | null
          adjuster_phone: string | null
          airtable_id: string | null
          alternative_contact_email: string | null
          alternative_contact_name: string | null
          alternative_contact_phone: string | null
          alternative_contact_relationship: string | null
          assigned_estimator: string | null
          assigned_supplementer: string | null
          assignee: string | null
          attachment_summary: Json | null
          attachments: Json | null
          carrier: string
          carrier_claim_number: string | null
          check_mailed_date: string | null
          checklist: Json | null
          claim_id: string
          contractor: string | null
          created_at: string | null
          customer_email: string | null
          customer_phone: string | null
          deductible: number | null
          depreciation: number | null
          depreciation_non_recoverable: number | null
          depreciation_recoverable: number | null
          design_center_meeting_date: string | null
          design_center_referral: boolean | null
          discord_channel_id: string | null
          discord_channel_name: string | null
          drive_folder: string | null
          drive_folder_id: string | null
          drive_folder_link: string | null
          estimate_submitted_date: string | null
          fields_raw: Json | null
          final_report_submitted_date: string | null
          first_name: string | null
          follow_up_phase: string | null
          follow_up_status: string | null
          housing_expiration_warning_sent: boolean | null
          id: string
          inspection: Json | null
          insurance_companies: Json | null
          insurance_email: string | null
          insurance_escalation_contacts: Json | null
          insurance_phone: string | null
          invoice_submitted_date: string | null
          last_follow_up_date: string | null
          last_name: string
          loss_date: string | null
          loss_type: string | null
          mitigation_approved_amount: number | null
          mitigation_submitted_amount: number | null
          mitigation_submitted_date: string | null
          mortgage: Json | null
          net_claim_sum: number | null
          next_follow_up_date: string | null
          next_payment_due: string | null
          notes: string | null
          o_and_p: number | null
          o_and_p_rate: number | null
          payment_followup_needed: boolean | null
          policy_number: string | null
          rcv: number | null
          referral_email: string | null
          referral_name: string | null
          referral_notes: string | null
          referral_phone: string | null
          referral_type: string | null
          risk_score: string | null
          specialty_approvals: Json | null
          stage: string | null
          status: string | null
          supervisor_contact: string | null
          supervisor_name: string | null
          supplement_approved_amount: number | null
          supplement_submitted_amount: number | null
          supplement_submitted_date: string | null
          total_approved_budget: number | null
          total_outstanding_payments: number | null
          total_payout: number | null
          updated_at: string | null
          work_orders: Json | null
        }
        Insert: {
          action_items?: Json | null
          acv?: number | null
          address?: string
          adjuster_contact_info?: Json | null
          adjuster_email?: string | null
          adjuster_name?: string | null
          adjuster_phone?: string | null
          airtable_id?: string | null
          alternative_contact_email?: string | null
          alternative_contact_name?: string | null
          alternative_contact_phone?: string | null
          alternative_contact_relationship?: string | null
          assigned_estimator?: string | null
          assigned_supplementer?: string | null
          assignee?: string | null
          attachment_summary?: Json | null
          attachments?: Json | null
          carrier?: string
          carrier_claim_number?: string | null
          check_mailed_date?: string | null
          checklist?: Json | null
          claim_id: string
          contractor?: string | null
          created_at?: string | null
          customer_email?: string | null
          customer_phone?: string | null
          deductible?: number | null
          depreciation?: number | null
          depreciation_non_recoverable?: number | null
          depreciation_recoverable?: number | null
          design_center_meeting_date?: string | null
          design_center_referral?: boolean | null
          discord_channel_id?: string | null
          discord_channel_name?: string | null
          drive_folder?: string | null
          drive_folder_id?: string | null
          drive_folder_link?: string | null
          estimate_submitted_date?: string | null
          fields_raw?: Json | null
          final_report_submitted_date?: string | null
          first_name?: string | null
          follow_up_phase?: string | null
          follow_up_status?: string | null
          housing_expiration_warning_sent?: boolean | null
          id?: string
          inspection?: Json | null
          insurance_companies?: Json | null
          insurance_email?: string | null
          insurance_escalation_contacts?: Json | null
          insurance_phone?: string | null
          invoice_submitted_date?: string | null
          last_follow_up_date?: string | null
          last_name: string
          loss_date?: string | null
          loss_type?: string | null
          mitigation_approved_amount?: number | null
          mitigation_submitted_amount?: number | null
          mitigation_submitted_date?: string | null
          mortgage?: Json | null
          net_claim_sum?: number | null
          next_follow_up_date?: string | null
          next_payment_due?: string | null
          notes?: string | null
          o_and_p?: number | null
          o_and_p_rate?: number | null
          payment_followup_needed?: boolean | null
          policy_number?: string | null
          rcv?: number | null
          referral_email?: string | null
          referral_name?: string | null
          referral_notes?: string | null
          referral_phone?: string | null
          referral_type?: string | null
          risk_score?: string | null
          specialty_approvals?: Json | null
          stage?: string | null
          status?: string | null
          supervisor_contact?: string | null
          supervisor_name?: string | null
          supplement_approved_amount?: number | null
          supplement_submitted_amount?: number | null
          supplement_submitted_date?: string | null
          total_approved_budget?: number | null
          total_outstanding_payments?: number | null
          total_payout?: number | null
          updated_at?: string | null
          work_orders?: Json | null
        }
        Update: {
          action_items?: Json | null
          acv?: number | null
          address?: string
          adjuster_contact_info?: Json | null
          adjuster_email?: string | null
          adjuster_name?: string | null
          adjuster_phone?: string | null
          airtable_id?: string | null
          alternative_contact_email?: string | null
          alternative_contact_name?: string | null
          alternative_contact_phone?: string | null
          alternative_contact_relationship?: string | null
          assigned_estimator?: string | null
          assigned_supplementer?: string | null
          assignee?: string | null
          attachment_summary?: Json | null
          attachments?: Json | null
          carrier?: string
          carrier_claim_number?: string | null
          check_mailed_date?: string | null
          checklist?: Json | null
          claim_id?: string
          contractor?: string | null
          created_at?: string | null
          customer_email?: string | null
          customer_phone?: string | null
          deductible?: number | null
          depreciation?: number | null
          depreciation_non_recoverable?: number | null
          depreciation_recoverable?: number | null
          design_center_meeting_date?: string | null
          design_center_referral?: boolean | null
          discord_channel_id?: string | null
          discord_channel_name?: string | null
          drive_folder?: string | null
          drive_folder_id?: string | null
          drive_folder_link?: string | null
          estimate_submitted_date?: string | null
          fields_raw?: Json | null
          final_report_submitted_date?: string | null
          first_name?: string | null
          follow_up_phase?: string | null
          follow_up_status?: string | null
          housing_expiration_warning_sent?: boolean | null
          id?: string
          inspection?: Json | null
          insurance_companies?: Json | null
          insurance_email?: string | null
          insurance_escalation_contacts?: Json | null
          insurance_phone?: string | null
          invoice_submitted_date?: string | null
          last_follow_up_date?: string | null
          last_name?: string
          loss_date?: string | null
          loss_type?: string | null
          mitigation_approved_amount?: number | null
          mitigation_submitted_amount?: number | null
          mitigation_submitted_date?: string | null
          mortgage?: Json | null
          net_claim_sum?: number | null
          next_follow_up_date?: string | null
          next_payment_due?: string | null
          notes?: string | null
          o_and_p?: number | null
          o_and_p_rate?: number | null
          payment_followup_needed?: boolean | null
          policy_number?: string | null
          rcv?: number | null
          referral_email?: string | null
          referral_name?: string | null
          referral_notes?: string | null
          referral_phone?: string | null
          referral_type?: string | null
          risk_score?: string | null
          specialty_approvals?: Json | null
          stage?: string | null
          status?: string | null
          supervisor_contact?: string | null
          supervisor_name?: string | null
          supplement_approved_amount?: number | null
          supplement_submitted_amount?: number | null
          supplement_submitted_date?: string | null
          total_approved_budget?: number | null
          total_outstanding_payments?: number | null
          total_payout?: number | null
          updated_at?: string | null
          work_orders?: Json | null
        }
        Relationships: []
      }
      cost_payments: {
        Row: {
          airtable_id: string | null
          amount: number | null
          check_number: string | null
          claim_id: string | null
          created_at: string | null
          date: string | null
          fields_raw: Json | null
          id: string
          job_costing_id: string | null
          notes: string | null
          payment_method: string | null
          payment_name: string | null
          status: string | null
          updated_at: string | null
        }
        Insert: {
          airtable_id?: string | null
          amount?: number | null
          check_number?: string | null
          claim_id?: string | null
          created_at?: string | null
          date?: string | null
          fields_raw?: Json | null
          id?: string
          job_costing_id?: string | null
          notes?: string | null
          payment_method?: string | null
          payment_name?: string | null
          status?: string | null
          updated_at?: string | null
        }
        Update: {
          airtable_id?: string | null
          amount?: number | null
          check_number?: string | null
          claim_id?: string | null
          created_at?: string | null
          date?: string | null
          fields_raw?: Json | null
          id?: string
          job_costing_id?: string | null
          notes?: string | null
          payment_method?: string | null
          payment_name?: string | null
          status?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cost_payments_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cost_payments_job_costing_id_fkey"
            columns: ["job_costing_id"]
            isOneToOne: false
            referencedRelation: "job_costing"
            referencedColumns: ["id"]
          },
        ]
      }
      email_config: {
        Row: {
          access_token: string
          airtable_id: string | null
          created_at: string | null
          email_address: string
          fields_raw: Json | null
          id: string
          provider: string
          refresh_token: string | null
          status: string | null
          token_expiry: string | null
          updated_at: string | null
        }
        Insert: {
          access_token: string
          airtable_id?: string | null
          created_at?: string | null
          email_address: string
          fields_raw?: Json | null
          id?: string
          provider: string
          refresh_token?: string | null
          status?: string | null
          token_expiry?: string | null
          updated_at?: string | null
        }
        Update: {
          access_token?: string
          airtable_id?: string | null
          created_at?: string | null
          email_address?: string
          fields_raw?: Json | null
          id?: string
          provider?: string
          refresh_token?: string | null
          status?: string | null
          token_expiry?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      financial_ledger: {
        Row: {
          airtable_id: string | null
          amount: number | null
          category: string | null
          check_number: string | null
          claim_id: string | null
          created_at: string | null
          date: string | null
          description: string | null
          direction: string | null
          entry_name: string | null
          entry_type: string | null
          fields_raw: Json | null
          id: string
          module_id: string | null
          payer_payee: string | null
          reconciled: boolean | null
          reconciled_date: string | null
          updated_at: string | null
        }
        Insert: {
          airtable_id?: string | null
          amount?: number | null
          category?: string | null
          check_number?: string | null
          claim_id?: string | null
          created_at?: string | null
          date?: string | null
          description?: string | null
          direction?: string | null
          entry_name?: string | null
          entry_type?: string | null
          fields_raw?: Json | null
          id?: string
          module_id?: string | null
          payer_payee?: string | null
          reconciled?: boolean | null
          reconciled_date?: string | null
          updated_at?: string | null
        }
        Update: {
          airtable_id?: string | null
          amount?: number | null
          category?: string | null
          check_number?: string | null
          claim_id?: string | null
          created_at?: string | null
          date?: string | null
          description?: string | null
          direction?: string | null
          entry_name?: string | null
          entry_type?: string | null
          fields_raw?: Json | null
          id?: string
          module_id?: string | null
          payer_payee?: string | null
          reconciled?: boolean | null
          reconciled_date?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "financial_ledger_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "financial_ledger_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      job_costing: {
        Row: {
          actual_cost: number | null
          approved_estimate_amount: number
          airtable_id: string | null
          claim_id: string | null
          cost_name: string | null
          created_at: string | null
          estimate_approved_date: string | null
          fields_raw: Json | null
          has_supplement: boolean
          id: string
          invoice_date: string | null
          invoice_number: string | null
          module_id: string | null
          notes: string | null
          payment_status: string | null
          scope_description: string | null
          submitted_estimate_amount: number
          supplement_approved_amount: number
          supplement_invoice_label: string | null
          supplement_invoice_mode: string
          trade_category: string | null
          updated_at: string | null
          variance: number | null
          variance_percent: number | null
          vendor_subcontractor: string | null
          xactimate_budget: number | null
        }
        Insert: {
          actual_cost?: number | null
          approved_estimate_amount?: number
          airtable_id?: string | null
          claim_id?: string | null
          cost_name?: string | null
          created_at?: string | null
          estimate_approved_date?: string | null
          fields_raw?: Json | null
          has_supplement?: boolean
          id?: string
          invoice_date?: string | null
          invoice_number?: string | null
          module_id?: string | null
          notes?: string | null
          payment_status?: string | null
          scope_description?: string | null
          submitted_estimate_amount?: number
          supplement_approved_amount?: number
          supplement_invoice_label?: string | null
          supplement_invoice_mode?: string
          trade_category?: string | null
          updated_at?: string | null
          variance?: number | null
          variance_percent?: number | null
          vendor_subcontractor?: string | null
          xactimate_budget?: number | null
        }
        Update: {
          actual_cost?: number | null
          approved_estimate_amount?: number
          airtable_id?: string | null
          claim_id?: string | null
          cost_name?: string | null
          created_at?: string | null
          estimate_approved_date?: string | null
          fields_raw?: Json | null
          has_supplement?: boolean
          id?: string
          invoice_date?: string | null
          invoice_number?: string | null
          module_id?: string | null
          notes?: string | null
          payment_status?: string | null
          scope_description?: string | null
          submitted_estimate_amount?: number
          supplement_approved_amount?: number
          supplement_invoice_label?: string | null
          supplement_invoice_mode?: string
          trade_category?: string | null
          updated_at?: string | null
          variance?: number | null
          variance_percent?: number | null
          vendor_subcontractor?: string | null
          xactimate_budget?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "job_costing_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_costing_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: true
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      materials: {
        Row: {
          airtable_id: string | null
          cost: number | null
          created_at: string | null
          fields_raw: Json | null
          id: string
          name: string | null
          notes: string | null
          project_id: string
          quantity: number | null
          status: string | null
          unit: string | null
          updated_at: string | null
          vendor: string | null
        }
        Insert: {
          airtable_id?: string | null
          cost?: number | null
          created_at?: string | null
          fields_raw?: Json | null
          id?: string
          name?: string | null
          notes?: string | null
          project_id: string
          quantity?: number | null
          status?: string | null
          unit?: string | null
          updated_at?: string | null
          vendor?: string | null
        }
        Update: {
          airtable_id?: string | null
          cost?: number | null
          created_at?: string | null
          fields_raw?: Json | null
          id?: string
          name?: string | null
          notes?: string | null
          project_id?: string
          quantity?: number | null
          status?: string | null
          unit?: string | null
          updated_at?: string | null
          vendor?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "materials_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      modules: {
        Row: {
          archived_at: string | null
          airtable_id: string | null
          approval_status: string | null
          bill_to: string | null
          claim_id: string
          created_at: string | null
          days_remaining: number | null
          days_running: number | null
          drive_module_folder_link: string | null
          end_date: string | null
          estimate_status: string
          estimated_finish_date: string | null
          estimated_items: string | null
          extension_history: Json | null
          facility_address: string | null
          fields_raw: Json | null
          gate_code: string | null
          housing_address: string | null
          housing_approval_date: string | null
          housing_approved: boolean | null
          housing_approved_date: string | null
          housing_contract_url: string | null
          housing_expiration_date: string | null
          housing_extension_date: string | null
          housing_request_date: string | null
          housing_requested: boolean | null
          housing_requested_date: string | null
          housing_type: string | null
          id: string
          job_costing_record_id: string | null
          lock_code: string | null
          module_name: string | null
          module_type: string | null
          next_payment_due: string | null
          notes: string | null
          number_of_bedrooms: number | null
          number_of_occupants: number | null
          packout_paid_date: string | null
          packout_submitted_date: string | null
          payment_amount: number | null
          payment_frequency: string | null
          reason_for_housing: string | null
          requested_end_date: string | null
          restoration_project_record_id: string | null
          start_date: string | null
          status: string | null
          storage_cost: number | null
          storage_due_date: string | null
          storage_type: string | null
          storage_unit_number: string | null
          supplement_status: string | null
          target_insurance_company_id: string | null
          update_frequency: string | null
          updated_at: string | null
          vendor: string | null
          vendor_contact: string | null
        }
        Insert: {
          archived_at?: string | null
          airtable_id?: string | null
          approval_status?: string | null
          bill_to?: string | null
          claim_id: string
          created_at?: string | null
          days_remaining?: number | null
          days_running?: number | null
          drive_module_folder_link?: string | null
          end_date?: string | null
          estimate_status?: string
          estimated_finish_date?: string | null
          estimated_items?: string | null
          extension_history?: Json | null
          facility_address?: string | null
          fields_raw?: Json | null
          gate_code?: string | null
          housing_address?: string | null
          housing_approval_date?: string | null
          housing_approved?: boolean | null
          housing_approved_date?: string | null
          housing_contract_url?: string | null
          housing_expiration_date?: string | null
          housing_extension_date?: string | null
          housing_request_date?: string | null
          housing_requested?: boolean | null
          housing_requested_date?: string | null
          housing_type?: string | null
          id?: string
          job_costing_record_id?: string | null
          lock_code?: string | null
          module_name?: string | null
          module_type?: string | null
          next_payment_due?: string | null
          notes?: string | null
          number_of_bedrooms?: number | null
          number_of_occupants?: number | null
          packout_paid_date?: string | null
          packout_submitted_date?: string | null
          payment_amount?: number | null
          payment_frequency?: string | null
          reason_for_housing?: string | null
          requested_end_date?: string | null
          restoration_project_record_id?: string | null
          start_date?: string | null
          status?: string | null
          storage_cost?: number | null
          storage_due_date?: string | null
          storage_type?: string | null
          storage_unit_number?: string | null
          supplement_status?: string | null
          target_insurance_company_id?: string | null
          update_frequency?: string | null
          updated_at?: string | null
          vendor?: string | null
          vendor_contact?: string | null
        }
        Update: {
          archived_at?: string | null
          airtable_id?: string | null
          approval_status?: string | null
          bill_to?: string | null
          claim_id?: string
          created_at?: string | null
          days_remaining?: number | null
          days_running?: number | null
          drive_module_folder_link?: string | null
          end_date?: string | null
          estimate_status?: string
          estimated_finish_date?: string | null
          estimated_items?: string | null
          extension_history?: Json | null
          facility_address?: string | null
          fields_raw?: Json | null
          gate_code?: string | null
          housing_address?: string | null
          housing_approval_date?: string | null
          housing_approved?: boolean | null
          housing_approved_date?: string | null
          housing_contract_url?: string | null
          housing_expiration_date?: string | null
          housing_extension_date?: string | null
          housing_request_date?: string | null
          housing_requested?: boolean | null
          housing_requested_date?: string | null
          housing_type?: string | null
          id?: string
          job_costing_record_id?: string | null
          lock_code?: string | null
          module_name?: string | null
          module_type?: string | null
          next_payment_due?: string | null
          notes?: string | null
          number_of_bedrooms?: number | null
          number_of_occupants?: number | null
          packout_paid_date?: string | null
          packout_submitted_date?: string | null
          payment_amount?: number | null
          payment_frequency?: string | null
          reason_for_housing?: string | null
          requested_end_date?: string | null
          restoration_project_record_id?: string | null
          start_date?: string | null
          status?: string | null
          storage_cost?: number | null
          storage_due_date?: string | null
          storage_type?: string | null
          storage_unit_number?: string | null
          supplement_status?: string | null
          target_insurance_company_id?: string | null
          update_frequency?: string | null
          updated_at?: string | null
          vendor?: string | null
          vendor_contact?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "modules_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
        ]
      }
      mortgage_releases: {
        Row: {
          airtable_id: string | null
          check_date: string | null
          check_number: string | null
          claim_id: string | null
          completion_percent: number | null
          contact_email: string | null
          contact_name: string | null
          contact_phone: string | null
          created_at: string | null
          cumulative_released: number | null
          deposit_date: string | null
          documents_submitted: boolean | null
          documents_submitted_date: string | null
          fields_raw: Json | null
          id: string
          inspection_company: string | null
          inspection_date: string | null
          inspection_required: boolean | null
          inspection_status: string | null
          loan_number: string | null
          mortgage_company: string | null
          release_amount: number | null
          release_name: string | null
          release_number: number | null
          release_status: string | null
          remaining_held: number | null
          request_date: string | null
          total_held_by_mortgage: number | null
          updated_at: string | null
        }
        Insert: {
          airtable_id?: string | null
          check_date?: string | null
          check_number?: string | null
          claim_id?: string | null
          completion_percent?: number | null
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string | null
          cumulative_released?: number | null
          deposit_date?: string | null
          documents_submitted?: boolean | null
          documents_submitted_date?: string | null
          fields_raw?: Json | null
          id?: string
          inspection_company?: string | null
          inspection_date?: string | null
          inspection_required?: boolean | null
          inspection_status?: string | null
          loan_number?: string | null
          mortgage_company?: string | null
          release_amount?: number | null
          release_name?: string | null
          release_number?: number | null
          release_status?: string | null
          remaining_held?: number | null
          request_date?: string | null
          total_held_by_mortgage?: number | null
          updated_at?: string | null
        }
        Update: {
          airtable_id?: string | null
          check_date?: string | null
          check_number?: string | null
          claim_id?: string | null
          completion_percent?: number | null
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string | null
          cumulative_released?: number | null
          deposit_date?: string | null
          documents_submitted?: boolean | null
          documents_submitted_date?: string | null
          fields_raw?: Json | null
          id?: string
          inspection_company?: string | null
          inspection_date?: string | null
          inspection_required?: boolean | null
          inspection_status?: string | null
          loan_number?: string | null
          mortgage_company?: string | null
          release_amount?: number | null
          release_name?: string | null
          release_number?: number | null
          release_status?: string | null
          remaining_held?: number | null
          request_date?: string | null
          total_held_by_mortgage?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "mortgage_releases_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
        ]
      }
      payments_log: {
        Row: {
          added_by: string | null
          airtable_id: string | null
          amount: number | null
          check_number: string | null
          claim_id: string
          created_at: string | null
          fields_raw: Json | null
          id: string
          invoice_number: string | null
          module_id: string | null
          notes: string | null
          payment_date: string | null
          payment_due_date: string | null
          payment_method: string | null
          payment_status: string | null
          reimbursement_amount: number | null
          reimbursement_date: string | null
          updated_at: string | null
          vendor: string | null
        }
        Insert: {
          added_by?: string | null
          airtable_id?: string | null
          amount?: number | null
          check_number?: string | null
          claim_id: string
          created_at?: string | null
          fields_raw?: Json | null
          id?: string
          invoice_number?: string | null
          module_id?: string | null
          notes?: string | null
          payment_date?: string | null
          payment_due_date?: string | null
          payment_method?: string | null
          payment_status?: string | null
          reimbursement_amount?: number | null
          reimbursement_date?: string | null
          updated_at?: string | null
          vendor?: string | null
        }
        Update: {
          added_by?: string | null
          airtable_id?: string | null
          amount?: number | null
          check_number?: string | null
          claim_id?: string
          created_at?: string | null
          fields_raw?: Json | null
          id?: string
          invoice_number?: string | null
          module_id?: string | null
          notes?: string | null
          payment_date?: string | null
          payment_due_date?: string | null
          payment_method?: string | null
          payment_status?: string | null
          reimbursement_amount?: number | null
          reimbursement_date?: string | null
          updated_at?: string | null
          vendor?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payments_log_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_log_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      phases: {
        Row: {
          airtable_id: string | null
          created_at: string | null
          end_date: string | null
          fields_raw: Json | null
          id: string
          name: string | null
          notes: string | null
          project_id: string
          sort_order: number | null
          start_date: string | null
          status: string | null
          updated_at: string | null
        }
        Insert: {
          airtable_id?: string | null
          created_at?: string | null
          end_date?: string | null
          fields_raw?: Json | null
          id?: string
          name?: string | null
          notes?: string | null
          project_id: string
          sort_order?: number | null
          start_date?: string | null
          status?: string | null
          updated_at?: string | null
        }
        Update: {
          airtable_id?: string | null
          created_at?: string | null
          end_date?: string | null
          fields_raw?: Json | null
          id?: string
          name?: string | null
          notes?: string | null
          project_id?: string
          sort_order?: number | null
          start_date?: string | null
          status?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "phases_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_expenses: {
        Row: {
          airtable_id: string | null
          amount: number | null
          category: string | null
          claim_id: string | null
          created_at: string | null
          date: string | null
          expense_name: string | null
          fields_raw: Json | null
          id: string
          module_id: string | null
          notes: string | null
          payment_method: string | null
          reimbursable: boolean | null
          updated_at: string | null
          vendor: string | null
        }
        Insert: {
          airtable_id?: string | null
          amount?: number | null
          category?: string | null
          claim_id?: string | null
          created_at?: string | null
          date?: string | null
          expense_name?: string | null
          fields_raw?: Json | null
          id?: string
          module_id?: string | null
          notes?: string | null
          payment_method?: string | null
          reimbursable?: boolean | null
          updated_at?: string | null
          vendor?: string | null
        }
        Update: {
          airtable_id?: string | null
          amount?: number | null
          category?: string | null
          claim_id?: string | null
          created_at?: string | null
          date?: string | null
          expense_name?: string | null
          fields_raw?: Json | null
          id?: string
          module_id?: string | null
          notes?: string | null
          payment_method?: string | null
          reimbursable?: boolean | null
          updated_at?: string | null
          vendor?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "project_expenses_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_expenses_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          actual_billed: number | null
          actual_labor_cost: number | null
          actual_material_cost: number | null
          actual_other_cost: number | null
          airtable_id: string | null
          claim_id_text: string | null
          confidence_score: number | null
          created_at: string | null
          currency: string | null
          due_date: string | null
          encircle_notes: string | null
          estimate_approved_date: string | null
          estimate_status: string | null
          estimate_total: number | null
          external_key: string | null
          fields_raw: Json | null
          id: string
          imported_at: string | null
          module_record_id: string | null
          name: string
          next_step: string | null
          operation_status: string | null
          owner: string | null
          priority: string | null
          profitability_notes: string | null
          scope_notes: string | null
          source_report_file: string | null
          source_report_type: string | null
          status: string | null
          status_label: string | null
          sub_cost: number | null
          summary: string | null
          updated_at: string | null
        }
        Insert: {
          actual_billed?: number | null
          actual_labor_cost?: number | null
          actual_material_cost?: number | null
          actual_other_cost?: number | null
          airtable_id?: string | null
          claim_id_text?: string | null
          confidence_score?: number | null
          created_at?: string | null
          currency?: string | null
          due_date?: string | null
          encircle_notes?: string | null
          estimate_approved_date?: string | null
          estimate_status?: string | null
          estimate_total?: number | null
          external_key?: string | null
          fields_raw?: Json | null
          id?: string
          imported_at?: string | null
          module_record_id?: string | null
          name: string
          next_step?: string | null
          operation_status?: string | null
          owner?: string | null
          priority?: string | null
          profitability_notes?: string | null
          scope_notes?: string | null
          source_report_file?: string | null
          source_report_type?: string | null
          status?: string | null
          status_label?: string | null
          sub_cost?: number | null
          summary?: string | null
          updated_at?: string | null
        }
        Update: {
          actual_billed?: number | null
          actual_labor_cost?: number | null
          actual_material_cost?: number | null
          actual_other_cost?: number | null
          airtable_id?: string | null
          claim_id_text?: string | null
          confidence_score?: number | null
          created_at?: string | null
          currency?: string | null
          due_date?: string | null
          encircle_notes?: string | null
          estimate_approved_date?: string | null
          estimate_status?: string | null
          estimate_total?: number | null
          external_key?: string | null
          fields_raw?: Json | null
          id?: string
          imported_at?: string | null
          module_record_id?: string | null
          name?: string
          next_step?: string | null
          operation_status?: string | null
          owner?: string | null
          priority?: string | null
          profitability_notes?: string | null
          scope_notes?: string | null
          source_report_file?: string | null
          source_report_type?: string | null
          status?: string | null
          status_label?: string | null
          sub_cost?: number | null
          summary?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      reports: {
        Row: {
          airtable_id: string | null
          content: string | null
          created_at: string | null
          date: string | null
          fields_raw: Json | null
          file_url: string | null
          id: string
          name: string | null
          project_id: string
          type: string | null
          updated_at: string | null
        }
        Insert: {
          airtable_id?: string | null
          content?: string | null
          created_at?: string | null
          date?: string | null
          fields_raw?: Json | null
          file_url?: string | null
          id?: string
          name?: string | null
          project_id: string
          type?: string | null
          updated_at?: string | null
        }
        Update: {
          airtable_id?: string | null
          content?: string | null
          created_at?: string | null
          date?: string | null
          fields_raw?: Json | null
          file_url?: string | null
          id?: string
          name?: string | null
          project_id?: string
          type?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reports_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      system_logins: {
        Row: {
          airtable_id: string | null
          category: string | null
          created_at: string | null
          email: string | null
          fields_raw: Json | null
          id: string
          last_updated: string | null
          notes: string | null
          password: string | null
          status: string | null
          system_name: string | null
          updated_at: string | null
          updated_by: string | null
          url: string | null
          username: string | null
        }
        Insert: {
          airtable_id?: string | null
          category?: string | null
          created_at?: string | null
          email?: string | null
          fields_raw?: Json | null
          id?: string
          last_updated?: string | null
          notes?: string | null
          password?: string | null
          status?: string | null
          system_name?: string | null
          updated_at?: string | null
          updated_by?: string | null
          url?: string | null
          username?: string | null
        }
        Update: {
          airtable_id?: string | null
          category?: string | null
          created_at?: string | null
          email?: string | null
          fields_raw?: Json | null
          id?: string
          last_updated?: string | null
          notes?: string | null
          password?: string | null
          status?: string | null
          system_name?: string | null
          updated_at?: string | null
          updated_by?: string | null
          url?: string | null
          username?: string | null
        }
        Relationships: []
      }
      tasks: {
        Row: {
          airtable_id: string | null
          assignee: string | null
          created_at: string | null
          due_date: string | null
          fields_raw: Json | null
          id: string
          name: string | null
          notes: string | null
          phase_id: string | null
          project_id: string
          status: string | null
          updated_at: string | null
        }
        Insert: {
          airtable_id?: string | null
          assignee?: string | null
          created_at?: string | null
          due_date?: string | null
          fields_raw?: Json | null
          id?: string
          name?: string | null
          notes?: string | null
          phase_id?: string | null
          project_id: string
          status?: string | null
          updated_at?: string | null
        }
        Update: {
          airtable_id?: string | null
          assignee?: string | null
          created_at?: string | null
          due_date?: string | null
          fields_raw?: Json | null
          id?: string
          name?: string | null
          notes?: string | null
          phase_id?: string | null
          project_id?: string
          status?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tasks_phase_id_fkey"
            columns: ["phase_id"]
            isOneToOne: false
            referencedRelation: "phases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      team_members: {
        Row: {
          airtable_id: string | null
          created_at: string | null
          discord_user_id: string | null
          fields_raw: Json | null
          id: string
          name: string
          updated_at: string | null
        }
        Insert: {
          airtable_id?: string | null
          created_at?: string | null
          discord_user_id?: string | null
          fields_raw?: Json | null
          id?: string
          name: string
          updated_at?: string | null
        }
        Update: {
          airtable_id?: string | null
          created_at?: string | null
          discord_user_id?: string | null
          fields_raw?: Json | null
          id?: string
          name?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      updates_log: {
        Row: {
          airtable_id: string | null
          claim_id: string
          communication_from: string | null
          created_at: string | null
          created_by: string | null
          date: string | null
          draft: string | null
          fields_raw: Json | null
          id: string
          note_type: string | null
          notes: string | null
          sent_to: string | null
          summary: string | null
          update_type: string | null
          updated_at: string | null
          updated_by: string | null
        }
        Insert: {
          airtable_id?: string | null
          claim_id: string
          communication_from?: string | null
          created_at?: string | null
          created_by?: string | null
          date?: string | null
          draft?: string | null
          fields_raw?: Json | null
          id?: string
          note_type?: string | null
          notes?: string | null
          sent_to?: string | null
          summary?: string | null
          update_type?: string | null
          updated_at?: string | null
          updated_by?: string | null
        }
        Update: {
          airtable_id?: string | null
          claim_id?: string
          communication_from?: string | null
          created_at?: string | null
          created_by?: string | null
          date?: string | null
          draft?: string | null
          fields_raw?: Json | null
          id?: string
          note_type?: string | null
          notes?: string | null
          sent_to?: string | null
          summary?: string | null
          update_type?: string | null
          updated_at?: string | null
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "updates_log_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      remove_or_archive_service: {
        Args: { p_module_id: string }
        Returns: Json
      }
      restore_service: {
        Args: { p_module_id: string }
        Returns: Json
      }
      save_service_estimate: {
        Args: {
          p_approved_amount?: number
          p_approved_date?: string
          p_estimate_status?: string
          p_module_id: string
          p_submitted_amount?: number
        }
        Returns: Json
      }
      save_service_supplement: {
        Args: {
          p_amount?: number
          p_has_supplement: boolean
          p_label?: string
          p_mode?: string
          p_module_id: string
          p_supplement_status?: string
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
